on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6.3
      with:
        bundle: extension-manager.flatpak
        manifest-path: build-aux/com.mattjakeman.ExtensionManager.Devel.json
        cache-key: flatpak-builder-${{ github.sha }}
        run-tests: true
